# Generated by Django 2.1.2 on 2018-10-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptom',
            field=models.CharField(max_length=500),
        ),
    ]
