# Generated by Django 2.1.2 on 2018-10-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20181015_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.CharField(max_length=50),
        ),
    ]
