# Generated by Django 2.1.2 on 2018-10-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20181015_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.DateField(),
        ),
    ]
