# Generated by Django 2.1.2 on 2018-10-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20181015_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
