# Generated by Django 2.1.2 on 2018-10-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
