# Generated by Django 2.1.2 on 2018-10-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20181021_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
