# Generated by Django 2.1.2 on 2018-10-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20181021_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='rating',
        ),
    ]
