# Generated by Django 2.1.2 on 2018-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181010_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
