# Generated by Django 2.1.2 on 2018-10-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181010_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
