# Generated by Django 2.1.2 on 2018-10-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181010_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='modified_time',
        ),
    ]
